import random

from cube import cubeState, Move, Edge, Corner

from solver import checkWhiteCrossSolved,solveFirstLayer, solveSecondLayer, solveThirdLayer



def main():

    for test in range(1, 1001):

        cube = cubeState()

        # generate random 1000-move scramble
        scramble = tuple(
            random.choice(list(Move))
            for _ in range(1000)
        )

        print(f"\nTEST {test}")

        print(
            "Scramble:",
            " ".join(move.name for move in scramble)
        )

        cube = cube.applyMoves(scramble)

        # scramble moves should not count as solution moves
        cube.moveHistory = []

        print("After scramble:")
        print("White cross solved:", checkWhiteCrossSolved(cube))
        print("First layer solved:", cube.isFirstLayerSolved())

        #first layer
        cube = solveFirstLayer(cube)

        print("\nAfter first layer:")
        print("First layer solved:", cube.isFirstLayerSolved())

        assert cube.isFirstLayerSolved()

        #second layer
        cube = solveSecondLayer(cube)

        secondLayerSolved = (
            cube.isEdgeSolved(Edge.FL)
            and cube.isEdgeSolved(Edge.FR)
            and cube.isEdgeSolved(Edge.BL)
            and cube.isEdgeSolved(Edge.BR)
        )

        print("\nAfter second layer:")
        print("First layer still solved:", cube.isFirstLayerSolved())
        print("Second layer solved:", secondLayerSolved)

        assert cube.isFirstLayerSolved()

        assert secondLayerSolved

        #third layer
        cube = solveThirdLayer(cube)

        cubeSolved = (
            all(cube.isEdgeSolved(edge) for edge in Edge)
            and all(cube.isCornerSolved(corner) for corner in Corner)
        )

        print("\nAfter third layer:")
        print("Cube solved:", cubeSolved)

        # entire cube should now be solved
        assert cubeSolved   

        solutionMoves = cube.moveHistory.copy()

        print(
            "Solution:",
            " ".join(move.name for move in solutionMoves)
        )

        print("Solution move count:", len(solutionMoves))

        #replay verification

        verificationCube = cubeState()

        # recreate the exact same scramble
        verificationCube = verificationCube.applyMoves(scramble)

        # apply only the moves generated by the solver
        verificationCube = verificationCube.applyMoves(solutionMoves)

        replaySolved = (
            all(
                verificationCube.isEdgeSolved(edge)
                for edge in Edge
            )
            and all(
                verificationCube.isCornerSolved(corner)
                for corner in Corner
            )
        )

        print("Solution replay solved cube:", replaySolved)

        #proves the recorded move sequence actually works
        assert replaySolved

        print(f"TEST {test} PASSED")

    print("\nALL 1000 FULL-CUBE TESTS PASSED!")


if __name__ == "__main__":
    main()